ci: release before deploy since tag deploys are manual, release won't happen unless deploy is triggered

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -14,9 +14,9 @@ stages:
   - build
   - test
   - package
+  - release
   - deploy
   - post-deploy
-  - release
 
 variables:
   CI_TOOLS_VERSION: "v20"
@@ -263,6 +263,44 @@ verify-package-rpm:
     - test -d /usr/lib/comentario/templates
     - test -s /usr/lib/systemd/system/comentario.service
 
+release:
+  stage: release
+  image: registry.gitlab.com/gitlab-org/release-cli:latest
+  rules:
+    - if: $CI_COMMIT_TAG
+  before_script:
+    # Install curl
+    - apk add --no-cache curl
+  script:
+    # Strip the 'v' prefix from the version number
+    - ver_num="${VERSION#v}"
+    - package_registry_url="$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/comentario/$ver_num"
+    - basename="comentario_${ver_num}_linux_amd64"
+
+    # Upload the packages
+    - assets=""
+    - |
+      for f in "$basename.deb" "$basename.rpm" "$basename.tar.gz" "checksums.txt" "metadata.json"; do
+          echo "Uploading artifact $f to $package_registry_url"
+          curl -fs --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "dist/$f" "$package_registry_url/$f"
+      
+          # Accumulate assets JSON
+          [[ -n "$assets" ]] && assets="$assets,"
+          assets="$assets{\"name\":\"$f\",\"url\":\"$package_registry_url/$f\"}"
+      done
+
+    # Extract the release text from CHANGELOG.md
+    - awk "/^##\s*$VERSION/{flag=1; next} /^##/{flag=0} flag" CHANGELOG.md > release-text
+    - |
+      if [ ! -s release-text ]; then
+        echo "Failed to extract release text for $VERSION from CHANGELOG.md"
+        exit 1
+      fi
+
+    # Create a release
+    - echo "Creating release $CI_COMMIT_TAG"
+    - release-cli create --name "$CI_COMMIT_TAG" --tag-name "$CI_COMMIT_TAG" --description release-text --assets-link "[$assets]"
+
 # Deploy the dev branch to edge.comentario.app
 deploy-dev:
   stage: deploy
@@ -354,41 +392,3 @@ smoke-test:
     # Check basic redirections
     - checkRedirect http://$ENV_HOST/  https://$ENV_HOST/
     - checkRedirect https://$ENV_HOST/ /en/
-
-release:
-  stage: release
-  image: registry.gitlab.com/gitlab-org/release-cli:latest
-  rules:
-    - if: $CI_COMMIT_TAG
-  before_script:
-    # Install curl
-    - apk add --no-cache curl
-  script:
-    # Strip the 'v' prefix from the version number
-    - ver_num="${VERSION#v}"
-    - package_registry_url="$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/comentario/$ver_num"
-    - basename="comentario_${ver_num}_linux_amd64"
-
-    # Upload the packages
-    - assets=""
-    - |
-      for f in "$basename.deb" "$basename.rpm" "$basename.tar.gz" "checksums.txt" "metadata.json"; do
-          echo "Uploading artifact $f to $package_registry_url"
-          curl -fs --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "dist/$f" "$package_registry_url/$f"
-      
-          # Accumulate assets JSON
-          [[ -n "$assets" ]] && assets="$assets,"
-          assets="$assets{\"name\":\"$f\",\"url\":\"$package_registry_url/$f\"}"
-      done
-
-    # Extract the release text from CHANGELOG.md
-    - awk "/^##\s*$VERSION/{flag=1; next} /^##/{flag=0} flag" CHANGELOG.md > release-text
-    - |
-      if [ ! -s release-text ]; then
-        echo "Failed to extract release text for $VERSION from CHANGELOG.md"
-        exit 1
-      fi
-
-    # Create a release
-    - echo "Creating release $CI_COMMIT_TAG"
-    - release-cli create --name "$CI_COMMIT_TAG" --tag-name "$CI_COMMIT_TAG" --description release-text --assets-link "[$assets]"
