ci: add static binary tarball (resolves #50)

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -19,7 +19,7 @@ stages:
   - post-deploy
 
 variables:
-  CI_TOOLS_VERSION: "v24"
+  CI_TOOLS_VERSION: "v25"
   DEPLOYER_IMAGE: "alpine/k8s:1.28.2"
   # Namespace to deploy Kubernetes objects into
   NAMESPACE: ys-comentario
@@ -277,31 +277,36 @@ release:
     # Strip the 'v' prefix from the version number
     - ver_num="${VERSION#v}"
     - package_registry_url="$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/comentario/$ver_num"
-    - basename="comentario_${ver_num}_linux_amd64"
 
     # Upload the packages
-    - assets=""
     - |
-      for f in "$basename.deb" "$basename.rpm" "$basename.tar.gz" "checksums.txt" "metadata.json"; do
-          echo "Uploading artifact $f to $package_registry_url"
-          curl -fs --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "dist/$f" "$package_registry_url/$f"
-      
-          # Accumulate assets JSON
-          [[ -n "$assets" ]] && assets="$assets,"
-          assets="$assets{\"name\":\"$f\",\"url\":\"$package_registry_url/$f\"}"
-      done
+      jq -r '.[] | select(.type != "Binary") | .path' dist/artifacts.json | 
+          while read artifact; do
+              echo "Uploading artifact $artifact to $package_registry_url"
+              curl --no-progress-meter --fail‐with‐body \
+                  --header "JOB-TOKEN: $CI_JOB_TOKEN" \
+                  --upload-file "$artifact" "$package_registry_url/$(basename "$artifact")"
+          done
 
     # Extract the release text from CHANGELOG.md
     - awk "/^##\s+$VERSION/{flag=1; next} /^##\s+/{flag=0} flag" CHANGELOG.md > release-text
     - |
       if [[ ! -s release-text ]]; then
-        echo "Failed to extract release text for $VERSION from CHANGELOG.md"
-        exit 1
+          echo "Failed to extract release text for $VERSION from CHANGELOG.md"
+          exit 1
       fi
 
     # Create a release
-    - echo "Creating release $CI_COMMIT_TAG"
-    - release-cli create --name "$CI_COMMIT_TAG" --tag-name "$CI_COMMIT_TAG" --description release-text --assets-link "[$assets]"
+    - |
+      echo "Creating release $CI_COMMIT_TAG"
+      assets="$(jq -r --arg URL "$package_registry_url" '[.[] | select(.type != "Binary") | {name, url: "\($URL)/\(.name)"}]' dist/artifacts.json)"
+      echo "Publishing assets:"
+      echo "$assets"
+      release-cli create \
+          --name "$CI_COMMIT_TAG" \ 
+          --tag-name "$CI_COMMIT_TAG" \
+          --description release-text \
+          --assets-link "$assets"
 
 # Deploy the dev branch to edge.comentario.app
 deploy-dev:
